name: actions workflow
on: 
  push:
    branches:
      # - master # only if we push to the master branche
      # we can use patterns also
      - 'feature/*' # matches any branche that begin with feature but not feature/feaA/fhhf only one level
      # * matches any string except /
      - 'feature/**' # ** matches any string
      - '!feature/featc'
      # if we want to trigger our workflow in all branches except only one we can use branches-ignore
      # we can not have branches and branches-ignore in the same time, we have to choose
    # tags:
    #   - v1.*
    # # paths:
    # #   - '**.js' # matches any js file in our repo
    # paths-ignore:
    #   - 'docs/**' #matches any thing in the docs folder
  repository_dispatch:
    types: [build]
  # schedule: # this key will make use trigger our worklow in a certain schedule, its an array
  #   - cron: "0/5 * * * *" # the cron schedule expression: 5 things: at every 5 minutes
  #   - cron: "0/6 * * * *" #at every 6 minutes
  pull_request: 
    types: [closed, opened]
    branches:
      - master
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{github.event.client_payload.env}}
      - name: list files 
      # pwd --> /home/runner/work/github-actions/github-actions
      # ls --> nothingbecause github will not clone our repo in our working directory (in the VM)
        run: |
          pwd 
          ls -a
      - name: clone repo # this actions will clone our repo in our working directory in the VM so our workflow can acces it
        uses: actions/checkout@v2.3.4
      - name: list files after checkout
        run: |
          pwd 
          ls -a
      - name: JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1 # take a reference to an action
        #(username/reponame@ref to a branch or a version or a specific commit)
        with:
          who-to-greet: 'Rania BOLTANE'
      - name: Log greeting time # how we can acces to the output of a step
        run: echo "${{steps.greet.outputs.time}}"
